const fs=require('fs'),path=require('path');
const app=path.resolve(__dirname,'..');
const babel=require(app+'/node_modules/@babel/core');
const out='/tmp/pos-cache-browser-test';fs.mkdirSync(out,{recursive:true});
fs.copyFileSync(app+'/node_modules/idb/build/umd.js',out+'/idb.js');
function module(file,name){const src=fs.readFileSync(app+'/node_modules/@controleonline/'+file,'utf8');const {code}=babel.transformSync(src,{babelrc:false,configFile:false,presets:[app+'/node_modules/@babel/preset-env']});return `const ${name}=(()=>{const exports={};${code};return exports;})();`;}
const nonce=Date.now();
const script=`const require=id=>{if(id==='idb')return idb;if(id.includes('localDB'))return Local;if(id.includes('catalogCacheScope'))return {getCatalogCacheScope:async()=> 'browser-test-${nonce}'};if(id.includes('/api'))return {api:{}};throw Error(id);};
${module('ui-common/src/api/localDB.js','Local')}
${module('ui-products/src/react/utils/cachedCatalogActions.js','Cache')}
(async()=>{let calls=0;const getters={resourceEndpoint:'products',items:[],totalItems:0};const store={getters,actions:{setItems:v=>getters.items=v,setTotalItems:v=>getters.totalItems=v,setIsLoading:()=>{},setIsLoadingList:()=>{}}};const a=Cache.createCachedCatalogActions(store,3,'products',{fetch:async(_,q)=>{calls++;return {member:[{id:q.page,product:'Teste'}],totalItems:2};}});const query={company:3,page:1,itemsPerPage:1};const phase=new URL(location.href).searchParams.get('phase');const result=await a.getItems(query);if(phase==='read'){if(calls!==0||result.length!==2||result.catalogPage!==2)throw Error('Persistent hydration failed');document.querySelector('#result').textContent='PASS: IndexedDB persisted both pages across page reload; network calls: 0';}else{if(calls!==1)throw Error('First load must fetch once');await a.getItems({...query,page:2,append:true});const db=new Local.default({resourceEndpoint:'test_entities_${nonce}',columns:[{name:'type',sortable:true}],filters:{type:'food'}});await Promise.all([db.saveItems([{id:1,type:'food'},{id:2,type:'drink'}]),db.getCurrentVersion()]);const rows=await db.getItemsByFilters();if(rows.length!==1||rows[0].id!==1)throw Error('Entity filtering/open failed');document.querySelector('#result').textContent='PASS: native IndexedDB write, concurrent opening, schema upgrade and filtering; two catalog pages stored';}})().catch(e=>{document.querySelector('#result').textContent='FAIL: '+e.message;});`;
fs.writeFileSync(out+'/test.js',script);
fs.writeFileSync(out+'/index.html','<!doctype html><meta charset="utf-8"><title>Cache local — verificação</title><h1>Verificação do armazenamento local</h1><p id="result">Executando…</p><a href="/?phase=read">Reabrir e conferir persistência</a><script src="/idb.js"></script><script src="/test.js"></script>');
