# global-deploy-web.yml
# Orquestrador WEB (STAGING)

name: Global Deploy WEB

on:
  workflow_dispatch:
  push:
    branches: [staging]

permissions:
  contents: read
  actions: write

jobs:

  manager:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Web Manager STAGING
        run: |
          gh workflow run web-deploy-staging-manager-ctrl.yml --ref "${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  shop:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Web Shop STAGING
        run: |
          gh workflow run web-deploy-production-shop-ctrl.yml --ref "${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lavego:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Web Lavego STAGING
        run: |
          gh workflow run web-deploy-staging-app-lavego.yml --ref "${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
