import {StyleSheet} from 'react-native';

export const createStyles = colors => StyleSheet.create({
  page: {flex: 1, backgroundColor: colors.background},
  content: {padding: 20, gap: 18, width: '100%', maxWidth: 1100, alignSelf: 'center', paddingBottom: 48},
  hero: {gap: 10, paddingVertical: 12},
  eyebrow: {color: colors.primary, fontWeight: '700', fontSize: 12, letterSpacing: 1},
  title: {color: colors.text, fontSize: 25, fontWeight: '700'},
  subtitle: {color: colors.text, fontSize: 17, fontWeight: '600'},
  text: {color: colors.text, fontSize: 15, lineHeight: 23},
  muted: {color: colors.textSecondary, fontSize: 14, lineHeight: 22},
  notice: {color: colors.textSecondary, fontSize: 14, lineHeight: 22, borderLeftWidth: 3, borderColor: colors.primary, paddingLeft: 12, paddingVertical: 5},
  tabs: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  tab: {padding: 10, borderWidth: 1, borderColor: colors.border, borderRadius: 10},
  activeTab: {backgroundColor: colors.primary, borderColor: colors.primary},
  activeTabText: {color: '#FFFFFF'},
  card: {padding: 20, gap: 16, borderWidth: 1, borderColor: colors.border, borderRadius: 14},
  deviceCard: {padding: 14, gap: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 10},
  stack: {gap: 12},
  actions: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  button: {paddingVertical: 12, paddingHorizontal: 16, borderRadius: 8, backgroundColor: colors.primary, alignSelf: 'flex-start'},
  buttonText: {color: '#FFFFFF', fontWeight: '600', fontSize: 14},
  disabled: {opacity: 0.45},
  checkRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, paddingVertical: 8},
  checkLabel: {flex: 1, color: colors.text, fontSize: 15, lineHeight: 23},
  reviewRow: {paddingVertical: 9, borderBottomWidth: 1, borderColor: colors.border},
  input: {minHeight: 100, textAlignVertical: 'top', borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 12, color: colors.text},
  counts: {gap: 6},
});
