name: Deploy Project Shop Ctrl
on:
  push:
    branches: [production]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Creating Config
        run: |
          echo "const env = {\
          API_ENTRYPOINT: 'https://api.controleonline.com',\
          SOCKET: 'wss://api.controleonline.com',\
          APP_TYPE: 'SHOP',\
          ZOOM: 0.80,\
          NEW_RELIC:{\
            LICENSE_KEY:'${{ secrets.NEW_RELIC_LICENSE_KEY }}',\
            APPLICATION_ID:'${{ secrets.NEW_RELIC_APPLICATION_ID }}',\
            ACCOUNT_ID: '${{ secrets.NEW_RELIC_ACCOUNT_ID }}',\
            TRUST_KEY: '${{ secrets.NEW_RELIC_TRUST_KEY }}',\
            BEACON: '${{ secrets.NEW_RELIC_BEACON }}',\
            ERROR_BEACON: '${{ secrets.NEW_RELIC_ERROR_BEACON }}'\
          }\
          };\
          module.exports = { env };\
          " > ./config/env.local.js
      - name: Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --recursive --init --checkout
      - name: Install Dependencies
        run: npm install --legacy-peer-deps   
      - name: Fix Expo Dependencies
        run: npx expo install --fix
      - name: Build
        run: |
          npx expo export --platform web
      - name: Deploy
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.SHOP_HOST }}
          user: ${{ secrets.SHOP_USER }}
          password: ${{ secrets.SHOP_PASSWORD }}
          localDir: "./dist"
          remoteDir: "~/public_html"
          forceSsl: false
